server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name:

  datasource:
    driverClassName: org.postgresgit ql.Driver
    url: jdbc:postgresql://localhost:5432/quora
    username: postgres
    password: Prawasi50

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect